<?php

/**
* Implements hook_form_FORM_ID_alter
* Used to hide form elements in WPS
*/
function jamechanical_form_wps_node_form_alter(&$form, &$form_state){

    // Disable Welding Processes for JA Mechanical
    $form['field_gmaw']['#access']  = FALSE;
    $form['field_saw']['#access']  = FALSE;
    $form['field_paw']['#access']  = FALSE;
    $form['field_esw']['#access']  = FALSE;
    $form['field_fcaw']['#access']  = FALSE;
    $form['field_egw']['#access']  = FALSE;
    $form['field_ofw']['#access']  = FALSE;

  // Unset Values form Scope Checkbox
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Corrosion Resistance Overlay']);
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Hard - Facing Spray Fuse']);
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Hard - Facing Overlay']);
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Stud Welding']);
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Tube - Tubesheet']);
  unset($form['field_wps_scope'][LANGUAGE_NONE]['#options']['Tube Expansion Prior to Welding']);

}