<?php

/**
* Implements hook_form_FORM_ID_alter
* Used to hide form elements in WPS
*/
function jamechanical_form_wps_node_form_alter(&$form, &$form_state){
	//$form['actions']['preview']['#value'] = "Calculate";
    $form['field_gmaw']['#access']  = FALSE;
    $form['field_saw']['#access']  = FALSE;
    $form['field_paw']['#access']  = FALSE;
    $form['field_esw']['#access']  = FALSE;
    $form['field_fcaw']['#access']  = FALSE;
    $form['field_egw']['#access']  = FALSE;
    $form['field_ofw']['#access']  = FALSE;

    //GTAW Field access
    $form['field_gtaw']['und'][0]['field_weld_metal_thickness']['#access'] = FALSE;
    

    //SMAW Field Access
    $form['field_smaw']['und'][0]['field_weld_metal_thickness']['#access'] = FALSE;
    
}

/**
* Implements hook_form_FORM_ID_alter
* Used to hide form elements in PQR
*/
function jamechanical_form_pqr_node_form_alter(&$form, &$form_state){
	dpm($form['field_gtaw']);
	//$form['actions']['preview']['#value'] = "Calculate";
    $form['field_dummy_2']['#access']  = FALSE;
    //GTAW Field access
    $form['field_gtaw']['und'][0]['field_thickness_range_min']['#access'] = FALSE;
    $form['field_gtaw']['und'][0]['field_thickness_range_max']['#access'] = FALSE;


    //SMAW Field Access
    $form['field_smaw']['und'][0]['field_thickness_range_min']['#access'] = FALSE;
    $form['field_smaw']['und'][0]['field_thickness_range_max']['#access'] = FALSE;


}