<?php

/**
* Implements hook_form_FORM_ID_alter
* Used to hide form elements in WPS
*/
function jamechanical_form_wps_node_form_alter(&$form, &$form_state){

    // Disable Welding Processes for JA Mechanical
    $form['field_gmaw']['#access']  = FALSE;
    $form['field_saw']['#access']  = FALSE;
    $form['field_paw']['#access']  = FALSE;
    $form['field_esw']['#access']  = FALSE;
    $form['field_fcaw']['#access']  = FALSE;
    $form['field_egw']['#access']  = FALSE;
    $form['field_ofw']['#access']  = FALSE;

  // Unset Values form Scope Checkbox


}

/**
* Implements hook_form_FORM_ID_alter
* Used to hide form elements in PQR
*/
function jamechanical_form_pqr_node_form_alter(&$form, &$form_state){
	//dpm($form);
	//$form['actions']['preview']['#value'] = "Calculate";
    $form['revision_information']['#access'] = FALSE;
    $node = $form_state['node'];
    if(isset($node->nid)){
        $form['revision_information']['#access'] = TRUE;
        $form['revision_information']['#type'] = 'vertical_tabs';
        $form['revision_information']['revision']['#access'] = TRUE;
        $form['revision_information']['log']['#type'] = 'textfield';
        $form['revision_information']['log']['#title'] = 'Revision Number';
        $form['revision_information']['log']['#maxlength'] = 5;
        $form['revision_information']['log']['#description'] = 'Enter your revision number';
    }

}